In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'/Users/samuelthudi/TEST2/used_cars_data.csv')

In [3]:
df.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,mileage_num,engine_num,power_num,Brand,Model
0,Mumbai,2010,72000.0,CNG,Manual,First,5.0,5.51,1.75,26.60,998.0,58.16,maruti,wagon
1,Pune,2015,41000.0,Diesel,Manual,First,5.0,16.06,12.50,19.67,1582.0,126.20,hyundai,creta
2,Chennai,2011,46000.0,Petrol,Manual,First,5.0,8.61,4.50,18.20,1199.0,88.70,honda,jazz
3,Chennai,2012,87000.0,Diesel,Manual,First,7.0,11.27,6.00,20.77,1248.0,88.76,maruti,ertiga
4,Coimbatore,2013,40670.0,Diesel,Automatic,Second,5.0,53.14,17.74,15.20,1968.0,140.80,audi,a4

### Data Description

The data contains the different attributes of used cars sold in different locations. The detailed data dictionary is given below.

- Brand: brand name of the car
- Model Name: model name of the car
- Location: Location in which the car is being sold or is available for purchase (cities)
- Year: Manufacturing year of the car
- Kilometers_driven: The total kilometers driven in the car by the previous owner(s) in km
- Fuel_Type: The type of fuel used by the car (Petrol, Diesel, Electric, CNG, LPG)
- Transmission: The type of transmission used by the car (Automatic/Manual)
- Owner_Type: Type of ownership
- Mileage: The standard mileage offered by the car company in kmpl or km/kg
- Engine: The displacement volume of the engine in CC
- Power: The maximum power of the engine in bhp
- Seats: The number of seats in the car
- New_Price: The price of a new car of the same model in INR Lakhs (1 Lakh = 100,000 INR)
- Price: The price of the used car in INR Lakhs

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7252 entries, 0 to 7251
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Location           7252 non-null   str
 1   Year               7252 non-null   int64
 2   Kilometers_Driven  7251 non-null   float64
 3   Fuel_Type          7252 non-null   str
 4   Transmission       7252 non-null   str
 5   Owner_Type         7252 non-null   str
 6   Seats              7199 non-null   float64
 7   New_Price          7252 non-null   float64
 8   Price              6019 non-null   float64
 9   mileage_num        7169 non-null   float64
 10  engine_num         7206 non-null   float64
 11  power_num          7077 non-null   float64
 12  Brand              7252 non-null   str
 13  Model              7252 non-null   str
dtypes: float64(7), int64(1), str(6)
memory usage: 793.3 KB

In [6]:
df.isna().sum()

Location                0
Year                    0
Kilometers_Driven       1
Fuel_Type               0
Transmission            0
Owner_Type              0
Seats                  53
New_Price               0
Price                1233
mileage_num            83
engine_num             46
power_num             175
Brand                   0
Model                   0
dtype: int64

In [12]:
df[df.duplicated()==True]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,mileage_num,engine_num,power_num,Brand,Model
4781,Hyderabad,2007,52195.0,Petrol,Manual,First,5.0,4.36,1.75,19.7,796.0,46.3,maruti,alto
7077,Kolkata,2017,13000.0,Diesel,Manual,First,5.0,13.58,NaN,26.0,1498.0,98.6,honda,city

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
import matplotlib.pyplot as plt

In [17]:
df.describe()

,Year,Kilometers_Driven,Seats,New_Price,Price,mileage_num,engine_num,power_num
count,7250.000000,7249.000000,7197.000000,7250.000000,6018.000000,7167.000000,7204.000000,7075.000000
mean,2013.366207,57818.610843,5.280534,21.311791,9.480753,18.345458,1616.720433,112.775871
std,3.253715,37503.482838,0.809426,24.260176,11.188403,4.157736,595.327259,53.498756
min,1996.000000,171.000000,2.000000,3.910000,0.440000,6.400000,72.000000,34.200000
25%,2011.000000,34000.000000,5.000000,7.880000,3.500000,15.300000,1198.000000,75.000000
50%,2014.000000,53442.000000,5.000000,11.300000,5.640000,18.200000,1493.000000,94.000000
75%,2016.000000,73000.000000,5.000000,21.712500,9.950000,21.100000,1968.000000,138.100000
max,2019.000000,775000.000000,10.000000,375.000000,160.000000,33.540000,5998.000000,616.000000

In [25]:
df[df['Seats'].isna()==True]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Seats,New_Price,Price,mileage_num,engine_num,power_num,Brand,Model
194,Ahmedabad,2007,60006.0,Petrol,Manual,First,NaN,13.580,2.95,NaN,NaN,NaN,honda,city
208,Kolkata,2010,42001.0,Petrol,Manual,First,NaN,7.880,2.11,16.10,NaN,NaN,maruti,swift
229,Bangalore,2015,70436.0,Diesel,Manual,First,NaN,7.650,3.60,NaN,1498.0,99.0,ford,figo
733,Chennai,2006,97800.0,Petrol,Manual,Third,NaN,7.880,1.75,16.10,NaN,NaN,maruti,swift
749,Mumbai,2008,55001.0,Diesel,Automatic,Second,NaN,120.000,26.50,NaN,NaN,NaN,land,rover
1294,Delhi,2009,55005.0,Petrol,Manual,First,NaN,13.580,3.20,12.80,NaN,NaN,honda,city
1327,Hyderabad,2015,50295.0,Petrol,Manual,First,NaN,7.880,5.80,16.10,NaN,NaN,maruti,swift
1385,Pune,2004,115000.0,Petrol,Manual,Second,NaN,13.580,1.50,NaN,NaN,NaN,honda,city
1460,Coimbatore,2008,69078.0,Petrol,Manual,First,NaN,120.000,40.88,NaN,NaN,NaN,land,rover
1917,Jaipur,2005,88000.0,Petrol,Manual,Second,NaN,13.580,1.70,13.00,1493.0,100.0,honda,city
2074,Pune,2011,24255.0,Petrol,Manual,First,NaN,7.880,3.15,16.10,NaN,NaN,maruti,swift
2096,Coimbatore,2004,52146.0,Petrol,Manual,First,NaN,4.550,1.93,NaN,NaN,NaN,hyundai,santro
2264,Pune,2012,24500.0,Petrol,Manual,Second,NaN,8.525,2.95,18.30,NaN,NaN,toyota,etios
2325,Pune,2015,67000.0,Petrol,Manual,First,NaN,7.880,4.70,16.10,NaN,NaN,maruti,swift
2335,Mumbai,2007,55000.0,Petrol,Manual,Second,NaN,7.880,1.75,16.10,NaN,NaN,maruti,swift
2369,Chennai,2008,56000.0,Petrol,Manual,Second,NaN,7.880,1.50,19.50,1061.0,NaN,maruti,estilo
2530,Kochi,2014,64158.0,Diesel,Automatic,First,NaN,67.870,17.89,18.48,NaN,NaN,bmw,5
2542,Bangalore,2011,65000.0,Petrol,Manual,Second,NaN,4.550,3.15,NaN,NaN,NaN,hyundai,santro
2623,Pune,2012,95000.0,Diesel,Automatic,Second,NaN,67.870,18.00,18.48,NaN,NaN,bmw,5
2668,Kolkata,2014,32986.0,Petrol,Manual,First,NaN,7.880,4.24,16.10,NaN,NaN,maruti,swift
2737,Jaipur,2001,200000.0,Petrol,Manual,First,NaN,5.510,0.70,12.00,NaN,NaN,maruti,wagon
2780,Pune,2009,100000.0,Petrol,Manual,First,NaN,4.550,1.60,NaN,NaN,NaN,hyundai,santro
2842,Bangalore,2012,43000.0,Petrol,Manual,First,NaN,4.550,3.25,NaN,NaN,NaN,hyundai,santro
3272,Mumbai,2008,81000.0,Diesel,Automatic,Second,NaN,67.870,10.50,18.48,NaN,NaN,bmw,5
3404,Jaipur,2006,125000.0,Petrol,Manual,Fourth & Above,NaN,7.880,2.35,16.10,NaN,NaN,maruti,swift
3520,Delhi,2012,90000.0,Diesel,Automatic,First,NaN,67.870,14.50,18.48,NaN,NaN,bmw,5
3522,Kochi,2012,66400.0,Petrol,Manual,First,NaN,4.550,2.66,NaN,NaN,NaN,hyundai,santro
3800,Mumbai,2012,129000.0,Diesel,Automatic,First,NaN,35.290,7.00,12.80,2953.0,NaN,ford,endeavour
3810,Kolkata,2013,27000.0,Petrol,Automatic,First,NaN,33.510,11.99,14.00,NaN,NaN,honda,cr-v
3882,Kolkata,2010,40000.0,Petrol,Manual,Second,NaN,7.880,2.50,19.50,1061.0,NaN,maruti,estilo
4011,Pune,2011,45271.0,Diesel,Manual,First,NaN,8.600,2.60,20.30,NaN,NaN,fiat,punto
4152,Mumbai,2003,75000.0,Diesel,Automatic,Second,NaN,120.000,16.11,NaN,NaN,NaN,land,rover
4229,Bangalore,2005,79000.0,Petrol,Manual,Second,NaN,4.550,1.65,17.00,NaN,NaN,hyundai,santro
4577,Delhi,2012,72000.0,Diesel,Automatic,Third,NaN,67.870,13.85,18.48,NaN,NaN,bmw,5
4604,Pune,2011,98000.0,Petrol,Manual,First,NaN,9.600,3.15,16.70,NaN,NaN,honda,jazz
4697,Kochi,2017,17941.0,Petrol,Manual,First,NaN,8.600,3.93,15.70,NaN,NaN,fiat,punto
4712,Pune,2003,80000.0,Petrol,Manual,Second,NaN,4.550,0.90,17.00,NaN,NaN,hyundai,santro
4952,Kolkata,2010,47000.0,Petrol,Manual,First,NaN,8.600,1.49,14.60,NaN,NaN,fiat,punto
5015,Delhi,2006,63000.0,Petrol,Manual,First,NaN,7.880,1.60,16.10,NaN,NaN,maruti,swift
5185,Delhi,2012,52000.0,Petrol,Manual,First,NaN,7.880,3.65,16.10,NaN,NaN,maruti,swift
5270,Bangalore,2002,53000.0,Petrol,Manual,Second,NaN,13.580,1.85,NaN,NaN,NaN,honda,city
5893,Chennai,2008,51000.0,Petrol,Manual,Second,NaN,7.880,1.75,19.50,1061.0,NaN,maruti,estilo
6042,Bangalore,2009,72000.0,Petrol,Manual,Second,NaN,25.830,NaN,17.50,NaN,NaN,skoda,laura
6541,Bangalore,2012,56600.0,Diesel,Manual,First,NaN,8.525,NaN,23.59,NaN,NaN,toyota,etios
6544,Bangalore,2012,58000.0,Petrol,Automatic,Second,NaN,10.250,NaN,15.00,NaN,NaN,hyundai,i20
6632,Kolkata,2016,27000.0,Diesel,Manual,First,NaN,18.865,NaN,NaN,NaN,NaN,mahindra,tuv
6642,Bangalore,2009,150000.0,Diesel,Automatic,Second,NaN,67.870,NaN,18.48,NaN,NaN,bmw,5
6650,Kolkata,2015,36009.0,Petrol,Manual,First,NaN,7.880,NaN,16.10,NaN,NaN,maruti,swift
6676,Jaipur,2010,65000.0,Petrol,Manual,Third,NaN,8.600,NaN,14.60,NaN,NaN,fiat,punto
6684,Pune,2010,115000.0,Petrol,Manual,Second,NaN,7.880,NaN,16.10,NaN,NaN,maruti,swift
6879,Chennai,2009,95000.0,Diesel,Automatic,Second,NaN,67.870,NaN,18.48,NaN,NaN,bmw,5
6901,Kochi,2012,59311.0,Petrol,Manual,First,NaN,8.525,NaN,18.30,NaN,NaN,toyota,etios
6956,Kochi,2019,11574.0,Petrol,Manual,First,NaN,9.600,NaN,NaN,1199.0,88.7,honda,jazz

In [39]:
df_car_seats = df.groupby(['Brand','Model'],)['Seats'].median()

In [52]:
df["Seats"] = df.groupby(["Brand","Model"])["Seats"].transform(
    lambda x: x.fillna(x.median())
    )


cols_list = ["mileage_num", "engine_num", "power_num"]

for col in cols_list:
    df[col] = df.groupby(["Brand", "Model"])[col].transform(
        lambda x: x.fillna(x.median())
    )

df.isnull().sum()

Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Seats                   0
New_Price               0
Price                1232
mileage_num             9
engine_num              0
power_num               9
Brand                   0
Model                   0
dtype: int64

In [53]:
cols_list = ["mileage_num", "power_num"]

for col in cols_list:
    df[col] = df.groupby(["Brand"])[col].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Seats                   0
New_Price               0
Price                1232
mileage_num             1
engine_num              0
power_num               2
Brand                   0
Model                   0
dtype: int64

In [54]:
cols_list = ["mileage_num", "power_num"]

for col in cols_list:
    df[col] = df[col].fillna(df[col].median())

df.isnull().sum()

Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Seats                   0
New_Price               0
Price                1232
mileage_num             0
engine_num              0
power_num               0
Brand                   0
Model                   0
dtype: int64

In [55]:
df = df[df["Price"].notna()].copy()

In [56]:
df.isna().sum()

Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Seats                0
New_Price            0
Price                0
mileage_num          0
engine_num           0
power_num            0
Brand                0
Model                0
dtype: int64

In [57]:
X = df.drop(["Price"], axis=1)
y = df["Price"]

In [58]:
X = pd.get_dummies(
    X,
    columns=X.select_dtypes(include=["object", "category"]).columns.tolist(),
    drop_first=True,
)

X = X.astype(float)

X.head()

/var/folders/93/7yk4lch57yq_k8rwnqkn3j5h0000gn/T/ipykernel_61221/1088824906.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns=X.select_dtypes(include=["object", "category"]).columns.tolist(),

,Year,Kilometers_Driven,Seats,New_Price,mileage_num,engine_num,power_num,Location_Bangalore,Location_Chennai,Location_Coimbatore,...,Model_xenon,Model_xf,Model_xj,Model_xuv300,Model_xuv500,Model_xylo,Model_yeti,Model_z4,Model_zen,Model_zest
0,2010.0,72000.0,5.0,5.51,26.60,998.0,58.16,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015.0,41000.0,5.0,16.06,19.67,1582.0,126.20,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2011.0,46000.0,5.0,8.61,18.20,1199.0,88.70,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2012.0,87000.0,7.0,11.27,20.77,1248.0,88.76,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2013.0,40670.0,5.0,53.14,15.20,1968.0,140.80,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()

lin_reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import mean_squared_error # as mse


y_pred_train = lin_reg.predict(X_train)

In [62]:
mean_squared_error(y_train,y_pred_train)

17.3682246978953

In [63]:
from sklearn.metrics import r2_score
r2_score(y_train,y_pred_train)

0.8602271184362763

In [65]:
y_pred_test = lin_reg.predict(X_test)
print(mean_squared_error(y_test,y_pred_test))
print(r2_score(y_test,y_pred_test))

31.58020979237092
0.7488253404190859